DROP TABLE IF EXISTS ENTRIES;
DROP TABLE IF EXISTS ORDERS;
DROP TABLE IF EXISTS PICTURES;

-- Entry table
CREATE TABLE ENTRIES (
 ID INTEGER NOT NULL UNIQUE,
 STARTDATETIME INTEGER NOT NULL,
 ENDDATETIME INTEGER NOT NULL,
 CHAPTER TEXT NOT NULL,
 TITLE TEXT NOT NULL,
 DESCRIPTION TEXT,
 CONSTRAINT ENTRIES_PRIMARY_KEY PRIMARY KEY (ID)
);
 
-- Order table
CREATE TABLE ORDERS (
 ID INTEGER NOT NULL UNIQUE,
 ORDERDATE INTEGER NOT NULL,
 SUPPLIER TEXT NOT NULL,
 COST DECIMAL(3) NOT NULL,
 CONSTRAINT ENTRIES_PRIMARY_KEY PRIMARY KEY (ID)
);
 
-- Pictures table
CREATE TABLE PICTURES (
 ID INTEGER NOT NULL,
 PICTURE BLOB NOT NULL,
 DESCRIPTION TEXT,
 CONSTRAINT PICTURES_PRIMARY_KEY PRIMARY KEY (ID),
 FOREIGN KEY(ID) REFERENCES ENTRIES(ID)
);

/*
	Populate Fake Data - https://www.epochconverter.com/
*/
-- Entries table
INSERT INTO ENTRIES(ID, STARTDATETIME, ENDDATETIME, CHAPTER, TITLE, DESCRIPTION) VALUES
 (1, 154634400000, 154634760000, "Tail", "Ordered tail kit", "I ordered the tail kit today. So exciting!"),
 (2, 154643040000, 154643400000, "Wing", "Ordered wing kit", "I ordered the wing kit today. I'm so excited!"),
 (3, 154651680000, 154652040000, "Tail", "Tail kit arrived", "Oh boy! It's like Christmas at the Luckett house!");
-- Orders table
INSERT INTO ORDERS(ID, ORDERDATE, SUPPLIER, COST) VALUES
 (1, 154630080000, "Aircraft Spruce", 999.99),
 (2, 154638720000, "Wick's Aircraft Supply", 9999.99);